AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - vendor/**/*
    - bin/**/*

Style:
  Enabled: false

Metrics:
  Enabled: false

inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec